name: Mac OS C/C++ CI

on:
  workflow_dispatch:
      branches: [ feature ]
      

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: Install Qt
      uses: WillBrennan/yaqti
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'
        modules: 'qtcharts qtscript qtwebengine'
        
    - uses: actions/checkout@v3
    - name: qmake
      run: qmake -makefile
    - name: make
      run: make
  
    - uses: actions/upload-artifact@v3
      with:
        name: CS-Mult
        path: ./
